### ISSUE TITLE
Importing non-standard library python module

### ISSUE THREAD

**Issue by asrp** [google/grumpy#208]
Say `a.py` contains

    def foo(x):
        print(x)

and `b.py` contains

    import a
    a.foo(1)

How do I run `b.py`? (Is there a way?)

There doesn't seem to be an example of the intended way using grumpy or indication that its not possible in the README. `grumpc`'s command line arguments suggests that this may be possible.

(And if it is possible, what about compiling an entire module from Python to go instead of a single file?)

**Comment by trotterdylan** [comment]
This is possible and its done extensively within the standard library (e.g. the collections module imports itertools). Module imports translate into Go package imports with the prefix `grumpy/lib/`, so when you `import collections` in Python, the .go file will `import "grumpy/lib/collections"`.

Therefore, to work properly, everything to work properly, your compiled Go packages (a.a and b.a) will need to live in `$GOPATH/pkg/{arch}/grumpy/lib`. You can think of it as if the PYTHONPATH contained a single directory and all the modules had to coexist there.

It's easy to make this work in the current project directory structure by dropping your .py files into the lib directory. They will get picked up and built by `make` and then you can import those modules elsewhere. This setup is far from ideal and we plan on having a more flexible import system. See for example discussions [here](https://github.com/google/grumpy/issues/43) and [here](https://groups.google.com/d/topic/grumpy-users/JJFFube8qkM/discussion).

I'm going to close this for now since I think these requirements are captured elsewhere. Feel free to reopen if you don't think that's the case.
