### ISSUE TITLE
float.__str__ should return only 12 digits of precision

### ISSUE THREAD

**Issue by corona10** [google/grumpy#262]
`math.ldexp(0.125,1000)` should be `1.33938575898e+300`.
But grumpy results `1.3393857589828342e+300`.

**Comment by trotterdylan** [comment]
For CPython I get:

```
$ python
>>> math.ldexp(0.125,1000)
1.3393857589828342e+300
```

And for Grumpy:

```
$ echo 'import math; print math.ldexp(0.125,1000)' | make run
1.3393857589828342e+300
```

Where I do see your result is if I run:

```
python -c 'import math; print math.ldexp(0.125,1000)'
1.33938575898e+300
```

This has to do with the difference between `__str__` and `__repr__` for float. `__str__` seems to truncate a bit, whereas `__repr__` shows the exact result. From the CPython source:

```
static PyObject *
float_repr(PyFloatObject *v)
{
    return float_str_or_repr(v, 0, 'r');
}

static PyObject *
float_str(PyFloatObject *v)
{
    return float_str_or_repr(v, PyFloat_STR_PRECISION, 'g');
}
```

This in turn results in different behavior in PyOS_double_to_string() where repr uses 17 digits of precision (guaranteed to be able to represent the number exactly) and str uses `PyFloat_STR_PRECISION == 12` digits of precision.

So really the bug here is that Grumpy has no `float.__str__` and so falls back to `float.__repr__`. We should implement `float.__str__` to return only 12 digits of precision.

**Comment by corona10** [comment]
@trotterdylan Yes, you are right. 👍

**Comment by corona10** [comment]
@trotterdylan `float_str_or_repr` should be reimplementeed in python way.
When I read Cpython's implementations, it is little bits different between golang's `strconv.FormatFloat`.
