### ISSUE TITLE
Error in Makefile: recipe for target 'build/pkg/linux_amd64/__python__/test/test_bisect.a' failed

### ISSUE THREAD

**Issue by vbmade2000** [google/grumpy#276]
While executing `make` I am facing following error.
```
build/src/__python__/test/test_bisect/module.go:7: can't find import: "__python__/test"
Makefile:262: recipe for target 'build/pkg/linux_amd64/__python__/test/test_bisect.a' failed
make: *** [build/pkg/linux_amd64/__python__/test/test_bisect.a] Error 1
```

OS : Fedora release 25 (Twenty Five) 64 Bit
Python Version : 2.7

**Comment by trotterdylan** [comment]
Thanks for a reporting. That was caused by a recent change by me. Basically, the pydeps tools was marking all direct imports as dependencies of the module being scanned, but it was missing the root packages for imports of the form `import foo.bar`. So the module importing foo.bar would depend on bar, but not foo.

I think I've fixed it in 10001917d8eac7b22b697b764cb43e87a673a7ae. Let me know if you have any more trouble.
