### ISSUE TITLE
TypeError: cannot convert int to io.Writer (ioutil.Discard)

### ISSUE THREAD

**Issue by ns-cweber** [google/grumpy#42]
Trying to pass `ioutil.Discard` as an `io.Writer` argument raises a TypeError. Here's a simple example program:

```py
from __go__.io.ioutil import Discard as devnull
from __go__.fmt import Fprintln as fprintln

fprintln(devnull, "Hello, world")
```

The definition for `ioutil.Discard` is `var Discard io.Writer = devNull(0)`

**Comment by trotterdylan** [comment]
I took a stab at this. The basic problem is that for primitive types, `__native__` is returning a reflect.Value holding the basic type of the underlying storage, not the "real" type. Since devNull is defined as `type devNull int`, the reflect.Value for the Python devNull type `<type devNull>` is a plain old int, not a Go devNull.

The most obvious fix is to have `<type devNull>` define it's own __native__ that fetches the basic type and then converts it to devNull. I'm not happy with the way the code's structured so I'm going to think about how to rework it, but https://github.com/google/grumpy/pull/52 outlines the basic approach.

**Comment by trotterdylan** [comment]
This now works as expected.
